version: '3.8'

services:
  pronunciation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pronunciation-api-local
    ports:
      - "8000:8000"
    environment:
      # Azure Configuration
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION:-eastus}
      - AZURE_DEFAULT_LANGUAGE=${AZURE_DEFAULT_LANGUAGE:-cs-CZ}
      - AZURE_TIMEOUT=${AZURE_TIMEOUT:-30}
      
      # Application Configuration
      - APP_NAME=Pronunciation Assessment API (Local)
      - APP_VERSION=1.0.0
      - APP_DEBUG=true
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_CORS_ORIGINS=["http://localhost:3000","http://localhost:8080","http://127.0.0.1:3000","http://127.0.0.1:8080","capacitor://localhost","ionic://localhost","http://localhost","https://localhost"]
    
    volumes:
      # Монтируем код для hot reload в разработке
      - .:/app
      - /app/__pycache__
    
    restart: unless-stopped
    
    # Healthcheck для мониторинга
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - pronunciation-network


networks:
  pronunciation-network:
    driver: bridge
